version: "3.7"
volumes:
  api_node_modules:
  db1:
  opensearch-data1:
  opensearch-data2:
services:
  api:
    build: .
    command: yarn dev:container
    volumes: 
      - .:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    ports: 
      - "4000:4000"
      - "9222:9222"
    env_file:
      - ./.env
  db1:
      image: mongo:latest
      logging:
        driver: none
      restart: always
      ports: 
        - "27017:27017"
      env_file:
        - .env
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${DOCDB_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${DOCDB_INITDB_ROOT_PASSWORD}
      volumes:
        - db1:/data/db
        - ./ssl/mongo-keyfile:/mongo-keyfile
        - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      healthcheck:
        test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${DOCDB_INITDB_ROOT_PASSWORD} --quiet) -eq 1
        interval: 30s
        start_period: 60s
      expose:
        - "27017"
  opensearch-node1:
    image: opensearchproject/opensearch:2.0.1
    container_name: opensearch-node1
    logging:
      driver: none
    environment:
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600